dataset: "phoenixT"
work_dir: "/home/caffe/work/SLG/"
device: "cuda:0"
dataset_parameters:
  use_phoenix: False
  use_phoenixT: True
  use_how2sign: False
  use_asl: False
  use_csl: False
  use_csl-daily: False
  use_autsl: False
  is_processed: False
lr_parameters:
  epoch: 10
  learning_rate: 0.0001
  min_lr: 0
  weight_decay: 0.01
  milestones: [50,80]
  dropout: 0.3
  amp: True
  display_step: 100
  accumulate_step: 4
  batch_size: 8
  scheduler_timing: "step"
  scheduler_type: "CosineAnnealingWarmRestarts"
  grad_clip_norm: 1.0
  ema: False
  ema_beta: 0.999
  replacement_num_batches: 100

model:
  model_name: "google-bert/bert-base-multilingual-uncased"
  pose_dim: 100
  peft: True
  body_weights: 0.2
  hand_weights: 0.8
  face_weights: 0.2
  recon_weights: 0.0
  ce_weights: 1.0
  d_model: 512
  nhead: 8
  num_layers: 6
  max_len: 512






