dataset: "phoenixT"
work_dir: "/home/caffe/work/SLG/"
device: "cuda:0"
dataset_parameters:
  use_phoenix: False
  use_phoenixT: True
  use_how2sign: False
  use_asl: False
  use_csl: False
  use_csl-daily: False
  is_processed: False
lr_parameters:
  epoch: 100
  learning_rate : 0.0001
  min_lr: 0.000001
  weight_decay: 0.001
  milestones: [50,80]
  dropout: 0.3
  amp: True
  display_step: 100
  accumulation_step: 1
  batch_size: 32
  scheduler_timing: "epoch"
  scheduler_type: "CosineAnnealingLR"
  grad_clip_norm: 1.0
  ema: False
  ema_beta: 0.999
  replacement_num_batches: 100
loss_parameters:
    recon_pos_weight: 1.0
    recon_dir_weight: 0.0
    vq_weight: 1.0
    vel_weight: 0.00
model:
  kl_weight: 0.2
  pose_dim: 252
  text_cond: False
  is_diffusion: False
  text_encoder_name: "openai/clip-vit-base-patch32"
  body_weight: 0.3
  hand_weight: 0.7
  face_weight: 0.5
  recon_weight: 1.0
  length_weight: 0.0
  diffusion_weight: 1.0
  constractive_weight: 0.0
  constractive_temp:  0.07
  encoder:
    z_dim: 64
    q_input_dim: 252
    kv_input_dim: 252
    d_model: 512
    nhead: 8
    num_layers: 2
    pose_num_layers: 2
    pose_nhead: 8
    ffn_mult: 4
    dropout: 0.1
    activation: "gelu"
    window_size: 13
    text_nhead: 4
    text_num_layers: 3
    num_queries: 64
  decoder:
    d_model: 256
    nhead: 8
    num_layers: 2
    ffn_mult: 2
    dropout: 0.1
    activation: "gelu"
  diffusion_config:
    is_text_cond: False
    model_dim: 512
    nhead: 8
    num_layers: 2
    ffn_mult: 4
    dropout: 0.1
    num_train_steps: 1000
    sampling_steps: 50
    ddim_eta: 0.0
    text_drop_prob: 0.1
    cfg_scale_text: 3.0
    freeze_text_encoder: True
    time_dim: 512
    pred_type: "eps"
    channel_mults: (1,2,4)
    use_attn_levels: (True,True,True)
  clip_text:
    num_joints: 50
    joint_dim: 3
    skeleton_d_model: 512
    skeleton_nhead: 8
    skeleton_num_layers: 2
    skeleton_ffn_mult: 4
    text_encoder_name: "openai/clip-vit-base-patch32"
    text_num_layers: 2
    text_nhead: 4
    text_ffn_mult: 4
    proj_dim: 512
    dropout: 0.1
    text_pooling: "mean"
    init_temperature: 0.07
    null_text_seq_len: 32



